server:
  port: 9090
  tomcat:
    max-swallow-size: -1
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/nxt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
      location: /
      file-size-threshold: 512KB
mybatis-plus:
  global-config:
    banner: false
logging:
  level:
    com.exam.nxt.mapper: debug

